bash/project: Add support for +project-name to create projects
The `prj' command now allows project names to be prefixed with a +,
this will cause the project to be created if it does not already
exist.  If the project already exists then we just switch to the
project as normal.

diff --git a/home/DOT_bash.d/apb-projects b/home/DOT_bash.d/apb-projects
--- a/home/DOT_bash.d/apb-projects
+++ b/home/DOT_bash.d/apb-projects
@@ -91,12 +91,42 @@ function prj ()
         return ${status}
     fi
 
+    create_project=no
+    if [ "${project:0:1}" == "+" ]
+    then
+        project=${project:1}
+        create_project=yes
+
+        if [ -z "${project}" ]
+        then
+            echo "Invalid project name: +"
+            return 1
+        fi
+    fi
+
     # Switch project, handling error case.
     _apb-project_switch-project ${project}
     status=$?
     if [ $status != 0 ]
     then
-        echo "No project: ${project}"
+        if [ $create_project == yes ]
+        then
+            mkdir $APB_PROJECT_DIR/$project
+            status=$?
+            if [ $status != 0 ]
+            then
+                echo "Failed to create project: ${project}"
+                return $status
+            fi
+            _apb-project_switch-project ${project}
+            status=$?
+        fi
+
+        if [ $status != 0 ]
+        then
+            echo "No project: ${project}"
+            return ${status}
+        fi
     fi
     return ${status}
 }
